### ISSUE TITLE
HA 0.96+ Compatibility - Change to Climate 1.0

### ISSUE THREAD

**Issue by SmbKiwi** [nikrolls/homeassistant-goldair-climate#19]
Hi Nik

With HA 0.96 onwards, the Climate component has been changed (Climate 1.0 - see here: https://github.com/home-assistant/home-assistant/pull/23899 and changes to /tuya/climate.py file  ). Since the Goldair Climate uses the Climate Component, upgrading to HA 0.96 will likely break your component. 

Could you please update it. Thanks very much.

**Comment by SmbKiwi** [comment]
Hi Nik

I've spent some time working out how to make your project (forked from your version 0.01 not the later 0.03 version) work with Climate 1.0. I didn't know anything about Python but have worked it out and got it working. Have a look: https://github.com/SmbKiwi/homeassistant-goldair-heater/tree/v2.0

**Comment by nikrolls** [comment]
@SmbKiwi Hi, as you'll see in a couple of other messages, I didn't realise there was activity here. At some point I updated the code myself but never got around to updating the repository (lots of other things going on in life). The latest release contains that code and some other improvements to work towards supporting more device types (I have a dehumidifier and a fan I want to integrate).

**Comment by nikrolls** [comment]
Closing as this is no longer an issue.
