### ISSUE TITLE
Dehumidifier fault code is not surfaced

### ISSUE THREAD

**Issue by make-all** [nikrolls/homeassistant-goldair-climate#25]
I can see the tank full status is detected in the code, and made available as the "fault" attribute.

However, as this is not part of the standard climate API, the fault attribute is not showing up in the Home Assistant interface.

Maybe this could be made available as a sensor as well?  I'd like to be able to use this as a condition in my automations, also to trigger notifications.

**Comment by nikrolls** [comment]
@make-all I agree! I've been pondering ways to surface this. I could at the very least surface it as an "error" property, but HA really needs to add some kind of error state to climate integrations.

**Comment by nikrolls** [comment]
@make-all There is a new `error` attribute on dehumidifiers and heaters that can be monitored to detect if there's something wrong, including the tank being full or missing on dehumidifiers. You can use this in automations or, if you want it as a stand-alone entity, create a template sensor that surfaces it.
