### ISSUE TITLE
Workaround for HACS symlink issue

### ISSUE THREAD

**Issue by make-all** [nikrolls/homeassistant-goldair-climate#29]
In reference to hacs/integration Issue [#1115](https://github.com/hacs/integration/issues/1115)

If you make translations/en.json the "master" copy, and make strings.json the symlink, then installing from HACS seems to work on 0.109.x

If you choose to do this, then probably updating hacs.json to make 0.109.0 the minimum version is advisable, as installation will be broken under earlier versions for the same reason installation in 0.109.x currently is.

**Comment by nikrolls** [comment]
Thanks, I'll give this a go and see how HA likes it. Currently I'm copying files manually for release - not too painful for now.

**Comment by make-all** [comment]
I guess this can be closed now, as this component is included in HACS
