### ISSUE TITLE
"Unavailable" heater despite working well most of the time

### ISSUE THREAD

**Issue by charlietomo** [nikrolls/homeassistant-goldair-climate#3]
I've got two GPPH610 heaters and have them both connected to wifi and home assistant. As per the [other issue thread](https://github.com/nikrolls/homeassistant-goldair-heater/issues/1), they are now working well...most of the time.

At seemingly random times, I get `Unavailable` in home assistant:

![screen shot 2018-08-21 at 11 33 46 am](https://user-images.githubusercontent.com/19795112/44372226-0aeeb300-a537-11e8-8663-6cea30379eaa.png)

The details show when it drops off, in this example both before 11pm and after 11am:

![screen shot 2018-08-21 at 11 34 04 am](https://user-images.githubusercontent.com/19795112/44372237-1641de80-a537-11e8-91cf-9d408e63f39e.png)

They are still connected to wifi. 

I have a perhaps related issue whereby the heaters also sometimes "randomly" turn off. I will go back into a room and the heater display will either be blank, or `E1` will display which suggests some kind of error. This may or may not be related, but is an annoyance and I mention in case potential to be linked. I have removed one of the heaters from home assistant and I still got the random turn off issue.

A couple of other potentially pertinent bits of info.

- my Unifi wireless logs show each heater sending >15MB / day of data UP, which seems a lot? By comparison the DOWN is ~1MB / day.
- physically powering off the heater and then turning it on causes the heater to reconnect and become available within home assistant as expected

Errors in home assistant logs:

![screen shot 2018-08-21 at 11 44 53 am](https://user-images.githubusercontent.com/19795112/44372368-af70f500-a537-11e8-9774-49b242c9fe6a.png)

I have access to another machine, could I troubleshoot this by trying to send manual commands or similar? 

Have your heaters been rock solid?

**Comment by nikrolls** [comment]
@charlietomo My apologies, I didn't notice this. I know it's been a long time, but are you still getting this issue? I've released an update that brings everything up to scratch with the latest version of Home Assistant, and I've integrated into HACS now so I can keep things fresh.

**Comment by charlietomo** [comment]
Hi @nikrolls I actually got rid of both these heaters because I found them unreliable (unrelated to this plugin). They kept turning off or getting the E1 error, which was an issue trying to keep a nursery warm overnight. Good work on updating things but I won't be able to test!

**Comment by nikrolls** [comment]
No worries! Thanks for the update.
